services:
  minio:
    image: firstfinger/minio:latest-amd64
    # image: firstfinger/minio:latest-arm64
    container_name: minio
    ports:
      - "9000:9000" # S3 API endpoint
      - "9001:9001" # Web Admin Console (UI)
      - "9002:9002" # Console backend API (required for UI)
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: mini@123
      # MINIO_ROOT_PASSWORD_HASH: # not support
    volumes:
      - ./data:/data
    restart: unless-stopped
